// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARLWp-HVWtH3wBEoWtE-xk4ipT4Ii0rns',
    appId: '1:398282951750:web:d17ba6032eb0cee8acce47',
    messagingSenderId: '398282951750',
    projectId: 'app-devocional-mobile',
    authDomain: 'app-devocional-mobile.firebaseapp.com',
    storageBucket: 'app-devocional-mobile.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVwaPGr6JcDsIpY1lBhBgTL0xOcYhi5nA',
    appId: '1:398282951750:android:751bda5ad681a10eacce47',
    messagingSenderId: '398282951750',
    projectId: 'app-devocional-mobile',
    storageBucket: 'app-devocional-mobile.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARLWp-HVWtH3wBEoWtE-xk4ipT4Ii0rns',
    appId: '1:398282951750:web:d9561b8e810f44a7acce47',
    messagingSenderId: '398282951750',
    projectId: 'app-devocional-mobile',
    authDomain: 'app-devocional-mobile.firebaseapp.com',
    storageBucket: 'app-devocional-mobile.firebasestorage.app',
  );
}
